build:
    dependencies:
            before:
                - sudo composer self-update
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
filter:
    excluded_paths:
        - tests/*
        - src/migrations/*
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_sniffer:
        config:
            standard: "PSR2"